name: Doctrine 2.6

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  create:
    tags:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/test
      with:
        doctrine_version: '2.6'
        php_version: '7.1'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        discord_webhook: ${{ secrets.DISCORD_WEBHOOK }}
