name: PHP 8.4

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  create:
    tags:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/test
      with:
        php_version: '8.4'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        discord_webhook: ${{ secrets.DISCORD_WEBHOOK }}
